{
 "title": "Envoy",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(envoy_cluster_upstream_rq[1m])",
     "legendFormat": "{{envoy_response_code}}"
    }
   ]
  },
  {
   "title": "Active & Pending request count",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "envoy_cluster_upstream_rq_active",
     "legendFormat": "rq_active"
    },
    {
     "expr": "envoy_cluster_upstream_rq_pending_active",
     "legendFormat": "rq_pending_active"
    }
   ]
  },
  {
   "title": "Circuit Breaker",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "envoy_cluster_circuit_breakers_default_cx_open",
     "legendFormat": "cx_open"
    },
    {
     "expr": "envoy_cluster_circuit_breakers_default_rq_pending_open",
     "legendFormat": "rq_pending_open"
    },
    {
     "expr": "envoy_cluster_circuit_breakers_default_cx_pool_open",
     "legendFormat": "cx_pool_open"
    },
    {
     "expr": "envoy_cluster_circuit_breakers_default_rq_open",
     "legendFormat": "rq_open"
    }
   ]
  },
  {
   "title": "Connection count",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "envoy_cluster_upstream_cx_active",
     "legendFormat": "active connection"
    },
    {
     "expr": "envoy_cluster_upstream_rq_pending_active",
     "legendFormat": "pending request connection"
    }
   ]
  },
  {
   "title": "Request pending overflow",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "rate(envoy_cluster_upstream_rq_pending_overflow[1m])",
     "legendFormat": "request pending overflow"
    },
    {
     "expr": "rate(envoy_cluster_upstream_rq_pending_failure_eject[1m])",
     "legendFormat": "request pending failure"
    }
   ]
  },
  {
   "title": "Request Timeout",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(envoy_cluster_upstream_rq_timeout[1m])",
     "legendFormat": "request timeout"
    }
   ]
  }
 ]
}