global:
  scrape_interval: 5s
  evaluation_interval: 5s
scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
        labels:
          service: prometheus
  - job_name: "frontend"
    static_configs:
      - targets: ["frontend:9901"]
        labels:
          service: frontend
    metrics_path: /stats/prometheus
