{
 "title": "Envoy",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "External API", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Request rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    { "expr": "rate(http_requests_total[1m])", "legendFormat": "{{handler}} - {{code}}" }
   ]
  },
  {
   "title": "Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(request_duration_seconds_sum[1m])\n/\nrate(request_duration_seconds_count[1m])",
     "legendFormat": "{{handler}}"
    }
   ]
  },
  { "title": "Sidecar", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(envoy_cluster_upstream_rq[1m])",
     "legendFormat": "{{envoy_cluster_name}} -- {{envoy_response_code}}"
    }
   ]
  },
  {
   "title": "Active & Pending request count",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "envoy_cluster_upstream_rq_active",
     "legendFormat": "{{envoy_cluster_name}} -- rq_active"
    },
    {
     "expr": "envoy_cluster_upstream_rq_pending_active",
     "legendFormat": "{{envoy_cluster_name}} -- rq_pending_active"
    }
   ]
  },
  {
   "title": "Circuit Breaker",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "envoy_cluster_circuit_breakers_default_cx_open",
     "legendFormat": "{{envoy_cluster_name}} -- cx_open"
    },
    {
     "expr": "envoy_cluster_circuit_breakers_default_rq_pending_open",
     "legendFormat": "{{envoy_cluster_name}} -- rq_pending_open"
    },
    {
     "expr": "envoy_cluster_circuit_breakers_default_cx_pool_open",
     "legendFormat": "{{envoy_cluster_name}} -- cx_pool_open"
    },
    {
     "expr": "envoy_cluster_circuit_breakers_default_rq_open",
     "legendFormat": "{{envoy_cluster_name}} -- rq_open"
    }
   ]
  },
  {
   "title": "Connection count",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 19 },
   "targets": [
    {
     "expr": "envoy_cluster_upstream_cx_active",
     "legendFormat": "{{envoy_cluster_name}} -- active connection"
    },
    {
     "expr": "envoy_cluster_upstream_rq_pending_active",
     "legendFormat": "{{envoy_cluster_name}} -- pending request connection"
    }
   ]
  },
  {
   "title": "Request pending overflow",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "rate(envoy_cluster_upstream_rq_pending_overflow[1m])",
     "legendFormat": "{{envoy_cluster_name}} -- request pending overflow"
    },
    {
     "expr": "rate(envoy_cluster_upstream_rq_pending_failure_eject[1m])",
     "legendFormat": "{{envoy_cluster_name}} -- request pending failure"
    }
   ]
  },
  {
   "title": "Request Timeout",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 28 },
   "targets": [
    {
     "expr": "rate(envoy_cluster_upstream_rq_timeout[1m])",
     "legendFormat": "{{envoy_cluster_name}} -- request timeout"
    }
   ]
  }
 ]
}