{
 "title": "Envoy",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Backend", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Request count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum without(instance, job)(http_requests_total)"
    },
    {
     "expr": "sum without(instance, job, code)(http_requests_total)",
     "legendFormat": "total"
    }
   ]
  },
  { "title": "Envoy", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "envoy_http_downstream_rq_xx{envoy_http_conn_manager_prefix=\"ingress_http\"}",
     "legendFormat": "{{envoy_response_code_class}}xx"
    },
    {
     "expr": "envoy_http_downstream_rq_http1_total{envoy_http_conn_manager_prefix=\"ingress_http\"}",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Retry count",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "envoy_cluster_upstream_rq_retry",
     "legendFormat": "retry count"
    },
    {
     "expr": "envoy_cluster_upstream_rq_retry_success",
     "legendFormat": "retry success"
    },
    {
     "expr": "envoy_cluster_upstream_rq_retry_limit_exceeded",
     "legendFormat": "retry limit exceeded"
    },
    {
     "expr": "envoy_cluster_upstream_rq_retry_overflow",
     "legendFormat": "retry overflow"
    }
   ]
  }
 ]
}