{
 "title": "Envoy",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(envoy_http_downstream_rq_xx{envoy_http_conn_manager_prefix=\"ingress_http\"}[1m])",
     "legendFormat": "{{envoy_response_code_class}}xx"
    }
   ]
  },
  {
   "title": "minRTT and sampleRTT",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "envoy_http_adaptive_concurrency_gradient_controller_min_rtt_msecs",
     "legendFormat": "min_rtt_msecs"
    },
    {
     "expr": "envoy_http_adaptive_concurrency_gradient_controller_sample_rtt_msecs",
     "legendFormat": "sample_rtt_msecs"
    }
   ]
  },
  {
   "title": "Total blocked requests",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "rate(envoy_http_adaptive_concurrency_gradient_controller_rq_blocked[1m])",
     "legendFormat": "rq_blocked"
    }
   ]
  },
  {
   "title": "Current concurrency limit",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "envoy_http_adaptive_concurrency_gradient_controller_concurrency_limit",
     "legendFormat": "concurrency_limit"
    },
    {
     "expr": "envoy_http_adaptive_concurrency_gradient_controller_burst_queue_size",
     "legendFormat": "burst_queue_size"
    }
   ]
  },
  {
   "title": "minRTT calculation is active",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "targets": [
    {
     "expr": "envoy_http_adaptive_concurrency_gradient_controller_min_rtt_calculation_active",
     "legendFormat": "min_rtt_calculation_active"
    }
   ]
  },
  {
   "title": "Active & Pending request count",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "envoy_cluster_upstream_rq_active",
     "legendFormat": "rq_active"
    },
    {
     "expr": "envoy_cluster_upstream_rq_pending_active",
     "legendFormat": "rq_pending_active"
    }
   ]
  },
  {
   "title": "Connection count",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
   "targets": [
    {
     "expr": "envoy_cluster_upstream_cx_active",
     "legendFormat": "active connection"
    },
    {
     "expr": "envoy_cluster_upstream_rq_pending_active",
     "legendFormat": "pending request connection"
    }
   ]
  }
 ]
}